version: '3'

services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - 'nexus-data:/nexus-data'
    ports:
      - '8081:8081'
      - '8082:8082'
  mongo-db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    
  frontend:
    image: 192.168.0.4:8082/deploy_module/docker_image_frontend:2.0.0
    ports:
      - '80:80'
  backend:
    image: 192.168.0.4:8082/deploy_module/docker_image_backend:1.1.0
    ports:
      - '4000:4000'

volumes:
  nexus-data: {}